VotingSimulator simulate -pl data/canada/canada_partylist.csv -s fpp -s pv -pp data/canada/canada_conditionalprobability.csv -sp data/canada/canada_spatial.csv -poll data/canada/canada_poll2011.csv -actual data/canada/canada_actual2011.csv -sc a -out data/canada/out_canada_2011.csv
VotingSimulator simulate -pl data/canada/canada_partylist.csv -s fpp -s pv -pp data/canada/canada_conditionalprobability.csv -sp data/canada/canada_spatial.csv -poll data/canada/canada_poll2008.csv -actual data/canada/canada_actual2008.csv -sc a -out data/canada/out_canada_2008.csv
VotingSimulator simulate -pl data/canada/canada_partylist.csv -s fpp -s pv -pp data/canada/canada_conditionalprobability.csv -sp data/canada/canada_spatial.csv -poll data/canada/canada_poll2006.csv -actual data/canada/canada_actual2006.csv -sc a -out data/canada/out_canada_2006.csv
VotingSimulator simulate -pl data/canada/canada_partylist.csv -s fpp -s pv -pp data/canada/canada_conditionalprobability.csv -sp data/canada/canada_spatial.csv -poll data/canada/canada_poll2004.csv -actual data/canada/canada_actual2004.csv -sc a -out data/canada/out_canada_2004.csv

VotingSimulator simulate -pl data/canada/canada_partylist.csv -s fpp -s pv -pp data/canada/canada_conditionalprobability.csv -sp data/canada/canada_spatial.csv -poll data/canada/canada_poll2011_opinion.csv -actual data/canada/canada_actual2011.csv -sc a -out data/canada/out_canada_2011_opinion.csv
VotingSimulator simulate -pl data/canada/canada_partylist.csv -s fpp -s pv -pp data/canada/canada_conditionalprobability.csv -sp data/canada/canada_spatial.csv -poll data/canada/canada_poll2008_opinion.csv -actual data/canada/canada_actual2008.csv -sc a -out data/canada/out_canada_2008_opinion.csv
VotingSimulator simulate -pl data/canada/canada_partylist.csv -s fpp -s pv -pp data/canada/canada_conditionalprobability.csv -sp data/canada/canada_spatial.csv -poll data/canada/canada_poll2006_opinion.csv -actual data/canada/canada_actual2006.csv -sc a -out data/canada/out_canada_2006_opinion.csv


pause